# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Task(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, uuid: str=None, link: str=None):  # noqa: E501
        """Task - a model defined in Swagger

        :param uuid: The uuid of this Task.  # noqa: E501
        :type uuid: str
        :param link: The link of this Task.  # noqa: E501
        :type link: str
        """
        self.swagger_types = {
            'uuid': str,
            'link': str
        }

        self.attribute_map = {
            'uuid': 'uuid',
            'link': 'link'
        }

        self._uuid = uuid
        self._link = link

    @classmethod
    def from_dict(cls, dikt) -> 'Task':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Task of this Task.  # noqa: E501
        :rtype: Task
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uuid(self) -> str:
        """Gets the uuid of this Task.


        :return: The uuid of this Task.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid: str):
        """Sets the uuid of this Task.


        :param uuid: The uuid of this Task.
        :type uuid: str
        """

        self._uuid = uuid

    @property
    def link(self) -> str:
        """Gets the link of this Task.


        :return: The link of this Task.
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link: str):
        """Sets the link of this Task.


        :param link: The link of this Task.
        :type link: str
        """

        self._link = link
