swagger: '2.0'
info:
  description: 'yes'
  version: 1.0.0
  title: Hack for the Future
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 127.0.0.1
basePath: /api/
tags:
  - name: workspaces
    description: Everything about your workspaces
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
  - name: topics
    description: Everything about your topics
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
  - name: materials
    description: Everything about your materials
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
  - name: tasks
    description: Everything about your tasks
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
schemes:
  - https
paths:
  /workspaces:
    get:
      tags:
        - workspaces
      summary: Lists all workspaces
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Workspace'
        '405':
          description: Invalid input
    post:
      tags:
        - workspaces
      summary: 'Create new workspace, accepts workspace name'
      consumes:
        - text
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Workspace'
        '405':
          description: Invalid input
  '/workspaces/{workspaceId}':
    get:
      tags:
        - workspaces
      summary: Get specified workspace by its UUID
      produces:
        - application/json
      parameters:
        - name: workspaceId
          in: path
          description: ID of workspace
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Workspace'
        '405':
          description: Invalid input
    put:
      tags:
        - workspaces
      summary: Update specified workspace by its UUID
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: workspaceId
          in: path
          description: ID of workspace
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Workspace'
        '405':
          description: Invalid input
    delete:
      tags:
        - workspaces
      summary: Delete specified workspace by its UUID
      parameters:
        - name: workspaceId
          in: path
          description: ID of workspace
          required: true
          type: string
      responses:
        '200':
          description: OK
        '405':
          description: Invalid input
  '/workspaces/{workspaceId}/topics':
    get:
      tags:
        - workspaces
      summary: Get all topics of the workspace specified by UUID
      produces:
        - application/json
      parameters:
        - name: workspaceId
          in: path
          description: ID of workspace
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Topic'
        '405':
          description: Invalid input
    post:
      tags:
        - workspaces
      summary: 'Create new topic, returns the topic'
      consumes:
        - text
      produces:
        - application/json
      parameters:
        - name: workspaceId
          in: path
          description: ID of workspace
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Topic'
        '405':
          description: Invalid input
  '/workspaces/{workspaceId}/topics/{topicId}':
    get:
      tags:
        - topics
      summary: Return specified topic
      produces:
        - application/json
      parameters:
        - name: workspaceId
          in: path
          description: ID of workspace
          required: true
          type: string
        - name: topicId
          in: path
          description: ID of topic
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Topic'
        '405':
          description: Invalid input
    put:
      tags:
        - topics
      summary: 'Update topic specified by id, return topic'
      consumes:
        - text
      produces:
        - application/json
      parameters:
        - name: workspaceId
          in: path
          description: ID of workspace
          required: true
          type: string
        - name: topicId
          in: path
          description: ID of topic
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Topic'
        '405':
          description: Invalid input
    delete:
      tags:
        - workspaces
      summary: Delete specified topic
      parameters:
        - name: workspaceId
          in: path
          description: ID of workspace
          required: true
          type: string
        - name: topicId
          in: path
          description: ID of topic
          required: true
          type: string
      responses:
        '200':
          description: OK
        '405':
          description: Invalid input
  '/workspaces/{workspaceId}/topics/{topicId}/materials':
    get:
      tags:
        - materials
      summary: Get all materials for a topic
      produces:
        - application/json
      parameters:
        - name: workspaceId
          in: path
          description: ID of workspace
          required: true
          type: string
        - name: topicId
          in: path
          description: ID of topic
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Material'
        '405':
          description: Invalid input
    post:
      tags:
        - materials
      summary: Create new material for the specified topic
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: workspaceId
          in: path
          description: ID of workspace
          required: true
          type: string
        - name: topicId
          in: path
          description: ID of topic
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Material'
        '405':
          description: Invalid input
  '/workspaces/{workspaceId}/topics/{topicId}/materials/{materialId}':
    get:
      tags:
        - materials
      summary: Return specified material
      produces:
        - application/json
      parameters:
        - name: workspaceId
          in: path
          description: ID of workspace
          required: true
          type: string
        - name: topicId
          in: path
          description: ID of topic
          required: true
          type: string
        - name: materialId
          in: path
          description: ID of material
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Material'
        '400':
          description: Invalid input
    put:
      tags:
        - materials
      summary: 'Update material specified by id, return material'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: workspaceId
          in: path
          description: ID of workspace
          required: true
          type: string
        - name: topicId
          in: path
          description: ID of topic
          required: true
          type: string
        - name: materialId
          in: path
          description: ID of material
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Material'
        '400':
          description: Invalid input
    delete:
      tags:
        - materials
      summary: Delete specified topic
      parameters:
        - name: workspaceId
          in: path
          description: ID of workspace
          required: true
          type: string
        - name: topicId
          in: path
          description: ID of topic
          required: true
          type: string
        - name: materialId
          in: path
          description: ID of material
          required: true
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: Invalid input
  '/workspaces/{workspaceId}/topics/{topicId}/tasks':
    get:
      tags:
        - tasks
      summary: Get all tasks for a topic
      produces:
        - application/json
      parameters:
        - name: workspaceId
          in: path
          description: ID of workspace
          required: true
          type: string
        - name: topicId
          in: path
          description: ID of topic
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Task'
        '405':
          description: Invalid input
    post:
      tags:
        - tasks
      summary: Create new task for the specified topic
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: workspaceId
          in: path
          description: ID of workspace
          required: true
          type: string
        - name: topicId
          in: path
          description: ID of topic
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Task'
        '405':
          description: Invalid input
  '/workspaces/{workspaceId}/topics/{topicId}/tasks/{taskId}':
    get:
      tags:
        - tasks
      summary: Return specified task
      produces:
        - application/json
      parameters:
        - name: workspaceId
          in: path
          description: ID of workspace
          required: true
          type: string
        - name: topicId
          in: path
          description: ID of topic
          required: true
          type: string
        - name: taskId
          in: path
          description: ID of task
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Task'
        '400':
          description: Invalid input
    put:
      tags:
        - tasks
      summary: 'Update task specified by id, return task'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: workspaceId
          in: path
          description: ID of workspace
          required: true
          type: string
        - name: topicId
          in: path
          description: ID of topic
          required: true
          type: string
        - name: taskId
          in: path
          description: ID of task
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Material'
        '400':
          description: Invalid input
    delete:
      tags:
        - materials
      summary: Delete specified task
      parameters:
        - name: workspaceId
          in: path
          description: ID of workspace
          required: true
          type: string
        - name: topicId
          in: path
          description: ID of topic
          required: true
          type: string
        - name: taskId
          in: path
          description: ID of task
          required: true
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: Invalid input
  '/workspaces/{workspaceId}/topics/{topicId}/tasks/{taskId}/submit':
    post:
      tags:
        - tasks
      summary: Submit the completed task
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: workspaceId
          in: path
          description: ID of workspace
          required: true
          type: string
        - name: topicId
          in: path
          description: ID of topic
          required: true
          type: string
        - name: taskId
          in: path
          description: ID of task
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              type: boolean
        '400':
          description: Invalid input
definitions:
  Answer:
    type: object
    properties:
      isCorrect:
        type: boolean
      text:
        type: string
      explanation:
        type: string
  Topic:
    type: object
    properties:
      uuid:
        type: string
      name:
        type: string
  Task:
    type: object
    properties:
      uuid:
        type: string
      link:
        type: string
  Question:
    type: object
    properties:
      uuid:
        type: string
      questionText:
        type: string
      answers:
        type: array
        items:
          $ref: '#/definitions/Answer'
  User:
    type: object
    properties:
      uuid:
        type: string
      name:
        type: string
  Material:
    type: object
    properties:
      uuid:
        type: string
      name:
        type: string
      link:
        type: string
      questions:
        type: array
        items:
          $ref: '#/definitions/Question'
      tasks:
        type: array
        items:
          $ref: '#/definitions/Task'
      topics:
        type: array
        items:
          $ref: '#/definitions/Topic'
  Workspace:
    type: object
    properties:
      uuid:
        type: string
      name:
        type: string
      admin:
        $ref: '#/definitions/User'
      students:
        type: array
        items:
          $ref: '#/definitions/User'
      materials:
        type: array
        items:
          $ref: '#/definitions/Material'
